const a = {
  blocks: [
    {
      key: 'ac4c8',
      text: "It's a doddle. Download the giffgaff app and follow the steps below to switch on WiFi Extra. ",
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '54eij',
      text: 'The instructions are a tad different between the current app and the beta app. Learn more about the beta app.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [
        {
          offset: 79,
          length: 30,
          key: 0,
        },
      ],
      data: {},
    },
    {
      key: 'ai6u',
      text: 'Current app',
      type: 'header-two',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'bsufl',
      text: 'Download the latest version of the giffgaff app for your phone.',
      type: 'ordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '93cfh',
      text: "If you haven't already, sign into the giffgaff app using your membername and password.",
      type: 'ordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '6pqjn',
      text: 'Open the menu and tap "WiFi Extra".',
      type: 'ordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'et50g',
      text: 'On iOS, tap "Install WiFi Extra settings". On Android toggle the switch to "On".',
      type: 'ordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '41np5',
      text: 'Beta app',
      type: 'header-two',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'erdps',
      text: "Opt into the beta app if you haven't already, and log in.",
      type: 'ordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [
        {
          offset: 0,
          length: 21,
          key: 1,
        },
      ],
      data: {},
    },
    {
      key: '63qpl',
      text: 'Tap "More" in the bottom-right.',
      type: 'ordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '3icfk',
      text: 'Tap "WiFi Extra" under the "Settings" header.',
      type: 'ordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '38ago',
      text: 'Tap "Install WiFi Extra".',
      type: 'ordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '2vp71',
      text: '',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '4eib6',
      text: 'The settings will be installed on your phone and will mean that future connections should be seamless.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: '7s35',
      text:
        'WiFi on the London Underground is provided by Virgin Media. We’ve also teamed up with O2 to provide access to roughly 8,000 secure hotspots around the UK. Both of these are absolutely free, and you can opt-in and out as you wish.',
      type: 'unstyled',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'fc65b',
      text: 'Related articles',
      type: 'header-two',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: {},
    },
    {
      key: 'cvuj1',
      text: 'Does giffgaff have an app?',
      type: 'unordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [
        {
          offset: 0,
          length: 26,
          key: 2,
        },
      ],
      data: {},
    },
    {
      key: '7uv86',
      text: 'Becoming a beta app tester',
      type: 'unordered-list-item',
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [
        {
          offset: 0,
          length: 26,
          key: 3,
        },
      ],
      data: {},
    },
  ],
  entityMap: {
    0: {
      type: 'LINK',
      mutability: 'MUTABLE',
      data: {
        url: 'https://www.giffgaff.com/help/articles/becoming-a-beta-app-tester',
      },
    },
    1: {
      type: 'LINK',
      mutability: 'MUTABLE',
      data: {
        url: 'https://www.giffgaff.com/help/articles/becoming-a-beta-app-tester',
      },
    },
    2: {
      type: 'LINK',
      mutability: 'MUTABLE',
      data: {
        url: 'https://www.giffgaff.com/help/articles/does-giffgaff-have-an-app',
      },
    },
    3: {
      type: 'LINK',
      mutability: 'MUTABLE',
      data: {
        url: 'https://www.giffgaff.com/help/articles/becoming-a-beta-app-tester',
      },
    },
  },
};
